name: Publish to npm

on:
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.head_ref == 'dev'
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: refs/heads/${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Bump version
        run: |
          # Get the PR title
          PR_TITLE="${{ github.event.pull_request.title }}"

          # Determine version type from PR title (major, minor, or patch)
          VERSION_TYPE="patch"
          if [[ "$PR_TITLE" =~ ^major: ]]; then
            VERSION_TYPE="major"
          elif [[ "$PR_TITLE" =~ ^minor: ]]; then
            VERSION_TYPE="minor"
          elif [[ "$PR_TITLE" =~ ^patch: ]]; then
            VERSION_TYPE="patch"
          fi

          echo "Determined version type: $VERSION_TYPE"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          pnpm version ${VERSION_TYPE}
          git push --follow-tags

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
